### ISSUE TITLE
POST /run raises a 500

### ISSUE THREAD

**Issue by CollingsKenny** [Better-Turnip-Exchange/BTE-REST-API#11] opened 2020-05-21 01:00 UTC
/run returns a 500 code.

**Steps to Reproduce**
1. Post a new where:

POST /villager
```json
{
	"villager_id" : "test",
	"price_threshold" : "500"
}
```
Res: 200

2. Post run where:
```
{
  params: {
    villager_id: 'test'
}}
```

res:
```json
{
    "detail": "Keyword filter failed: 'NoneType' object is not iterable"
}
```

**Comment by Zagan202** [comment] 2020-05-21 02:53
The issue the issue is the request body in `POST /villager` is incorrect and I've failed to capture that.

and example of a correct request body will be in this schema
```
{
  "villager_id": "BobJoe",
  "keywords": [
    "bells"
  ],
  "islands_visited": {},
  "price_threshold": 0
}
```

Since it failed to capture it `/run` was attempting to reference keys in the data that was there, in this case `keywords`

**Comment by Zagan202** [comment] 2020-05-21 02:59
After thinking about it a bit more I actually am going to move forward with having defaults in place on the backend so you may continue to send requests as you were.
Stand by.

**Comment by Zagan202** [comment] 2020-05-21 03:12
I'm retracting my first comment, although it is technically correct its too rigid of a design.
I push a fix to master that should default parameters in the request body with default data.

**Comment by Zagan202** [comment] 2020-05-21 03:13
https://github.com/Better-Turnip-Exchange/BTE-REST-API/commit/338034776d2ecd0618f23657f7ad4cebce01faa7

**Closed as completed** 2020-05-22 21:28 UTC
